hrms-project/hrmanagement_system/employee/urls.py
from . import views
from django.urls import path

app_name = 'employee'

urlpatterns = [
    path('home', views.homepage,name='home'),
    path('master', views.masterpage,name='master'),
    path('hrlogin', views.loginpage,name='hrlogin'),
    path('leave', views.leavepage,name='hrleave'),
    path('dashboard', views.dashboard,name='hrdashboard'),
    path('calender', views.calender,name='hrcalender'),
    path('attendence', views.attendence,name='hrattendence'),
    path('newpage', views.newpage,name='newpage'),
    path('hrsignup', views.hrsignup,name='hrsignup'),
    path('pending', views.pending,name='pending'),
    path('history', views.history,name='history'),
]

hrms-project/hrmanagement_system/employer/urls.py
from . import views
from django.urls import path

app_name = 'employer'

urlpatterns = [
    path('master', views.master,name='master'),
    path('home', views.homepage,name='home'),
    path('departmentlist', views.departmentList,name='departmentlist'),
    path('positionlist', views.positionList,name='positionlist'),
    path('deleteposition/<int:pid>', views.deleteposition,name='deleteposition'),
    path('updatePos', views.updatePos,name='updatePos'),
    path('deleteDepart/<int:pid>', views.deleteDepart,name='deleteDepart'),
    path('employeelist', views.employeeList,name='employeelist'),
    path('employeeadd', views.employeeAdd,name='employeeadd'),
    path('selectPos', views.selectPos,name='selectPos'),

    
]

hrms-project/hrmanagement_system/hrmanagement_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include('employee.urls')),
    path('employer/',include('employer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hrms-project/hrmanagement_system/employee/models.py
from django.db import models

# Create your models here.

hrms-project/hrmanagement_system/employee/views.py
from django.shortcuts import render

# Create your views here.


def homepage(request):
    return render(request,'employee/home.html')

def masterpage(request):
    return render(request,'employee/master.html')

def loginpage(request):
    return render(request,'employee/hrlogin.html')

def leavepage(request):
    return render(request,'employee/leave.html')

def dashboard(request):
    return render(request,'employee/dashboard.html')

def calender(request):
    return render(request,'employee/calender.html')

def attendence(request):
    return render(request,'employee/attendence.html')

def newpage(request):
    return render(request,'employee/newpage.html')

def hrsignup(request):
    return render(request,'employee/hrsignup.html')

def pending(request):
    return render(request,'employee/pending.html')  

def history(request):
    return render(request,'employee/history.html')

hrms-project/hrmanagement_system/templates/employee/calender.html
{% extends 'employee/master.html'%}

{% load static %}

{% block content %}

 
    <div class="container mt-5 pt-3">
      <!-- ============================== first row start====================================== -->
      <div class="row mt-3">
        <div class="col-md-12">
          <div class="card card border-0 box-shadow">
            <div class="card-header border-0">Work Calender</div>
            <div class="card-body">
              <div id="calendar"></div>
            </div>
          </div>
          </div>
        </div>
      </div>


      <div class="modal fade" id="event_entry_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel">Add New Event</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="img-container">
                <div class="row">
                  <div class="col-sm-12">  
                    <div class="form-group">
                      <label for="event_name">Event name</label>
                      <input type="text" name="event_name" id="event_name" class="form-control" placeholder="Enter your event name">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">  
                    <div class="form-group">
                      <label for="event_start_date">Event start</label>
                      <input type="date" name="event_start_date" id="event_start_date" class="form-control onlydatepicker" placeholder="Event start date">
                     </div>
                  </div>
                  <div class="col-sm-6">  
                    <div class="form-group">
                      <label for="event_end_date">Event end</label>
                      <input type="date" name="event_end_date" id="event_end_date" class="form-control" placeholder="Event end date">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" onclick="save_event()">Save Event</button>
            </div>
          </div>
        </div>
      </div>
  
{% endblock %}

hrms-project/hrmanagement_system/templates/employee/departmentList.html
{% extends 'employer/master.html'%}

{% load static %}

{% block content %}
<div class="container mt-5 pt-3">
<div class="row mt-4 ">
    <div class="col-sm-5">
      <div class="card border-0">
        <div class="card-header text-center bg-primary border-0 text-light  rounded-pill fs-5 ">Add New Department</div>
        <div class="card-body ">
         
            <form method="post" id="myForm">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="departmentAdd" class="form-label">Department Name </label>
                  <input type="text" class="form-control"  name="deptName">
                </div>
                
                <button type="submit" class="btn btn-outline-primary" name="submit">Submit</button>
              </form>

        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="card">
        <div class="card-header text-center bg-primary text-light fs-5 ">Department List</div>
        <div class="card-body">
            <table class="table ">
                <thead>
                  <tr>
                    <th>Sno</th>
                    <th>Department</th>
                    <th>Action</th>
                    
                  </tr>
                </thead>
                <tbody>
            {% for dep in department %}    
                  <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ dep.dpartment_name }}</td>
                    <td hidden>{{ dep.id }}</td>
                    <td><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="departFech()">edit</button> <a href="{% url 'employer:deleteDepart' dep.id %}" class="btn btn-outline-danger">Delete</a></td>
                  </tr>
                  {% endfor %}      
                </tbody>
              </table>
        </div>
      </div>
    </div>
  </div>
</div>


 <!-- Modal -->
 <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post">
              {% csrf_token %}
              <input type="hidden" name="dep_id" id="dep_id">
                <div class="mb-3">
                    <label for="departmentAdd" class="form-label">Department Name </label>
                    <input type="text" class="form-control" id="departmentAdd" name="deptName" >
                  </div> 
                
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" name="update">Update</button>
        </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    function departFech(){
      var selected_row = event.target.parentNode.parentNode
      var children = selected_row.childNodes
      // console.log(children)
      var modal_text =document.getElementById('departmentAdd') 
      var modal_hidden =document.getElementById('dep_id')
      modal_hidden.value =children[5].innerText
      modal_text.value =children[3].innerText
    }

  </script>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->



<script>
  $(document).ready(function () {
      
      $('#myForm').validate({
        
          rules: {
            deptName: {
                  required: true
              },
              
            
          },
          messages: {
            deptName: 'Please enter department name',
             
            
          }
         
      });
  });
</script>
{% endblock %}

hrms-project/hrmanagement_system/templates/employee/history.html
{% extends 'employee/master.html'%}

{% load static %}

{% block content %}

<section class="mt-5">
    <div class=" pt-5 text-center">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{% url 'employee:hrleave' %}" class="btn btn-outline-secondary">Apply Leave</a>
        <a  href="{% url 'employee:pending' %}" class="btn btn-outline-secondary">Pending</a>
        <a  href="{% url 'employee:history' %}" class="btn  btn-primary">History</a>
      </div>
    </div>
    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                    <div class="text-center" hidden>
                    <img src="{% static 'images/pending.jpg' %}" alt="" style="width:600px; height: 400px;">
                    <h5 class="text-muted">There are no pending records of any leave transaction</h5>
                    </div>
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              <span class="ms-0 text-muted">Category</span> <span class="ms-auto text-muted">Leave Type</span> <span class="ms-auto text-muted">No. of days</span> <span class="ms-auto text-success">APPROVED</span>
                            </button>
                          </h2>
                          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body list-group list-group-flush">
                                
                            <div class="list-group-item">
                            <div class="fs-6 text-muted">Duration : 07 Jun 2023(Session 1) to 07 Jun 2023 (Session 2)</div>
                            <div class="fs-6 text-muted">Reason : due to sever back pain consultation</div>
                            </div>
                            <div class="d-flex ">
                                <span class="p-2 ms-2 text-muted">Applied on</span> <span class="p-2 ms-auto"><a href="">View Details</a> </span>
                            </div>
                            </div>
                          </div>
                        </div>
                        
                        
                      </div>
                </div>
              </div>
            </div>
          
          </div>
        </div>
</section>

{% endblock %}  

hrms-project/hrmanagement_system/templates/employee/leave.html
{% extends 'employee/master.html'%}

{% load static %}


{% block content %}

<div class="container">
 <div class="mt-5 pt-5">
  <div class="row text-center">
    <div class="col-md-3 col-sm-6 mb-3">
      <div class="card">
        <div class="card-header">Casual Leave</div>
        <div class="card-body position-relative cont">
          <div class="overlay position-absolute top-0 start-0 end-0 bottom-0 bg-secondary  bg-opacity-0">
            <div class="text position-absolute   text-center text-light fs-5">
              <span class="fs-6">Remaning Leave</span>
              <div class="number">12</div>
            </div>
          </div>
          <img src="{% static 'images/calendar.png' %}" class="img-fluid my-img" alt="...">
          <div class="mt-3">
            <p>Available	: <span>12</span></p>
             <p>Taken	: <span>0</span></p>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 mb-3 ">
      <div class="card">
        <div class="card-header">Earned Leave</div>
        <div class="card-body position-relative cont">
          <div class="overlay position-absolute top-0 start-0 end-0 bottom-0 bg-secondary  bg-opacity-75">
            <div class="text position-absolute   text-center text-light fs-5">
              <span class="fs-6">Remaning Leave</span>
              <div class="number">2</div>
            </div>
          </div>
          <img src="{% static 'images/warning.png' %}" class="img-fluid my-img" alt="...">
          <div class="mt-3">
            <p>Available	:<span>2</span></p>
             <p>Taken	: <span>0</span></p>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 mb-3">
      <div class="card">
        <div class="card-header">Leave Without Pay</div>
        <div class="card-body position-relative cont">
          <div class="overlay position-absolute top-0 start-0 end-0 bottom-0 bg-secondary  bg-opacity-75">
            <div class="text position-absolute   text-center text-light fs-5">
              <span class="fs-6">Remaning Leave</span>
              <div class="number">0</div>
            </div>
          </div>
          <img src="{% static 'images/leave-131964752935242149.png' %}" class="img-fluid my-img" alt="...">
          <div class="mt-3">
            <p>Available	: <span>0</span></p>
             <p>Taken	: <span>0</span></p>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 mb-3">
      <div class="card">
        <div class="card-header">Sick Leave</div>
        <div class="card-body position-relative cont">
          <div class="overlay position-absolute top-0 start-0 end-0 bottom-0 bg-secondary  bg-opacity-75">
            <div class="text position-absolute   text-center text-light fs-5">
              <span class="fs-6">Remaning Leave</span>
              <div class="number">6</div>
            </div>
          </div>
        <img src="{% static 'images/stethoscope.png' %}" class="img-fluid my-img" alt="...">
        <div class="mt-3">
          <p>Available	: <span>6</span></p>
           <p>Taken	: <span>0</span></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center mt-5">

  
  <!-- <div class="btn-group text-center" role="group" aria-label="Basic checkbox toggle button group">
    <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off" checked>
    <label class="btn btn-outline-primary" for="btncheck1">Apply Leave</label>
  
    <input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off">
    <label class="btn btn-outline-primary" for="btncheck2">Pending</label>
  
    <input type="checkbox" class="btn-check" id="btncheck3" autocomplete="off">
    <label class="btn btn-outline-primary" for="btncheck3">History</label>
  </div> -->

  <div class="btn-group" role="group" aria-label="Basic example">
    <a href="{% url 'employee:hrleave' %}" class="btn btn-primary">Apply Leave</a>
    <a  href="{% url 'employee:pending' %}" class="btn btn-outline-secondary">Pending</a>
    <a  href="{% url 'employee:history' %}" class="btn btn-outline-secondary">History</a>
  </div>
</div>
  <div class="row mt-5 mb-5">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">Leave Application</div>
        <div class="card-body">
          <!-- <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Employee ID</label>
          </div> -->
          <div class="mb-3">
            <label for="exampleInputEmployeId" class="form-label">Employee ID</label>
            <input type="text" class="form-control w-25" id="exampleInputEmployeId"  disabled >
            
          </div>
          <div class="col-md-4">
            <label for="inputState" class="form-label">Leave Type</label>
            <select id="inputState" class="form-select">
              <option selected>Select</option>
              <option>Causal Leave</option>
              <option>Earned Leave</option>
              <option>Leave Without Pay</option>
              <option>Sick Leave</option>
            </select>
          </div>
          <div class="row mt-2">
           
            <div class="col-sm-5 mt-2">
              <div class="mb-2">
                <label for="fromDate" class="form-label">From Date</label>
               <input type="date" class="form-control" id="fromDate" >
              </div>
            </div>
            <div class="col-sm-5 mt-2">
              <div class="mb-2">
                <label for="session" class="form-label">Session</label>
                <select class="form-select" aria-label="Default select example">
                  <option value="1" selected>Session 1</option>
                  <option value="2">Session 2</option>
                </select>
              </div>
            </div>
          </div>

          <div class="row mt-3">
           
            <div class="col-sm-5 mt-2">
              <div class="mb-2">
                <label for="fromDate" class="form-label">To Date</label>
               <input type="date" class="form-control" id="fromDate" placeholder="name@example.com">
              </div>
            </div>
            <div class="col-sm-5 mt-2">
              <div class="mb-2">
                <label for="session" class="form-label">Session</label>
                <select class="form-select" aria-label="Default select example">
                  <option value="1" selected>Session 1</option>
                  <option value="2">Session 2</option>
                </select>
              </div>              
            </div>
          </div>
          
          <div class="form-floating mt-3">
            <input type="email" class="form-control w-25 border border-top-0 border-end-0 border-start-0 border-info border-2 rounded-0" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Notify</label>
          </div>
          <div class="mt-3">
            <label for="exampleNumber" class="form-label">Contact Number</label>
            <input type="number" class="form-control w-25" id="exampleNumber">
          </div>
          <div class="mt-3">
            <label for="exampleReson" class="form-label">Reson</label>
            <textarea class="form-control" placeholder="Enter a Reson" id="exampleReson" style="height: 100px"></textarea>
          </div>  
          <div class="mt-3">
            <label for="examplefile" class="form-label">Attach File</label>
            <input type="file" class="form-control" id="examplefile">
          </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
            <button class="btn btn-info me-md-2 text-light" type="button">submit</button>
            <button class="btn btn-outline-info " type="button">cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock %}

hrms-project/hrmanagement_system/templates/employee/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>dashboardfinal</title>

<!-- --------------------------bootstrap link--------------------------------------- -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  
<!-- --------------------------google font--------------------------------------- -->
  <link
  href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,700&display=swap"
  rel="stylesheet">

<!-- -------------------------------------fontawsome----------------------------------------- -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  
  
<!-- -----------------css link------------------------------------------- -->
  
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> --> -->


  <link rel="stylesheet" href="{% static 'style/dashboard.css' %}">

  <link rel="stylesheet" href="{% static 'style/calender.css' %}">

  <link rel="stylesheet" href="{% static 'style/attendence.css' %}">

  <link rel="stylesheet" href="{% static 'style/leave.css' %}">




<!-- -------------------------------------Calender-io css----------------------------------------- -->
 <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.0/main.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@4.0.0-alpha.3/dist/fullcalendar.min.css">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@4.0.0-alpha.3/dist/fullcalendar.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@4.0.0-alpha.3/dist/locales-all.js"></script>  -->


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
      
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>



<body>
  <nav class="navbar navbar-expand-lg  bg-light  fixed-top">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="#offcanvasScrolling" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand text-primary fs-3 fw-bold" href="#">HR<span class="text-uppercase text-dark fs-5"> Mithra</span></a>
      <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
        
        <!-- <form class="d-flex ms-auto mt-3 mt-lg-0" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      
      <div class="dropdown mx-lg-4">
        <button class="btn  dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-user"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="{% url 'employee:hrlogin' %}">Log Out</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Enable body scrolling</button> -->

<div class="offcanvas offcanvas-start sidebar-nav rounded-4 border-0 " data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header text-dark">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel"></h5>
    <!-- <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button> -->
  </div>
  <div class="offcanvas-body text-secondary">
    <ul class="navbar-nav" id="nav-bar-item">
      <li class="nav-item">
        <a class="nav-link d-flex " aria-current="page" href="{% url 'employee:hrdashboard' %}"><i class="fa-solid fa-house me-3 fs-6"></i>
        <p class="fs-6">Home</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex " href="{% url 'employee:hrcalender' %}"><i class="fa-solid fa-calendar-days me-3 fs-6"></i>
        <p class="fs-6">Calender</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex " href=""><i class="fa-solid fa-user-group me-3 fs-6"></i>
        <p class="fs-6">Talent Engage</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex " href="{% url 'employee:hrattendence' %}"><i class="fa-solid fa-chart-column me-3 fs-6"></i>
        <p class="fs-6">Attendence</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex " href="{% url 'employee:hrleave' %}"><i class="fa-solid fa-calendar-minus me-3 fs-6"></i> 
        <p class="fs-6">Leave apply</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex " href="{% url 'employee:newpage' %}"><i class="fa-solid fa-calendar-minus me-3 fs-6"></i> 
        <p class="fs-6">Request</p>
        </a>
      </li>
    </ul>
  </div>
</div>

  <main>
  {% block content %}

  {% endblock %}
  </main>

  <script src="{% static 'javascript/hover.js' %}"></script>
  
  <script src="{% static 'javascript/table.js' %}"></script>

<!-- --------------------------------------js file table------------------------------------------------------- -->

  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<!-- --------------------------------------js file calender------------------------------------------------------- -->

  <script src="{% static 'javascript/calender.js' %}"></script>  

<!-- --------------------------------------js file date------------------------------------------------------- -->

  <script src="{% static 'javascript/date.js' %}"></script>
<!-- --------------------------------------js file calender-io------------------------------------------------------- -->

  <!-- <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.0/main.js"></script> -->

<!-- --------------------------------------js file bootstrap------------------------------------------------------- -->

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

   
</body>
</html>

hrms-project/hrmanagement_system/templates/employee/pending.html
{% extends 'employee/master.html'%}

{% load static %}

{% block content %}

<section class="mt-5">
    <div class=" pt-5 text-center">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{% url 'employee:hrleave' %}" class="btn  btn-outline-secondary">Apply Leave</a>
        <a  href="{% url 'employee:pending' %}" class="btn btn-primary">Pending</a>
        <a  href="{% url 'employee:history' %}" class="btn btn-outline-secondary">History</a>
      </div>
    </div>
    <div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
                <div class="text-center">
                   
             <img src="{% static 'images/pending.jpg' %}" alt="" style="width:600px; height: 400px;">
             <h5 class="text-muted">There are no pending records of any leave transaction</h5>
            </div>
            </div>
          </div>
        </div>
      
      </div>
    </div>
</section>

{% endblock %}  