hrms-project/hrmanagement_system/employee/urls.py
from . import views
from django.urls import path

app_name = 'employee'

urlpatterns = [
    path('home', views.homepage,name='home'),
    path('master', views.masterpage,name='master'),
    path('hrlogin', views.loginpage,name='hrlogin'),
    path('leave', views.leavepage,name='hrleave'),
    path('dashboard', views.dashboard,name='hrdashboard'),
    path('calender', views.calender,name='hrcalender'),
    path('attendence', views.attendence,name='hrattendence'),
    path('newpage', views.newpage,name='newpage'),
    path('hrsignup', views.hrsignup,name='hrsignup'),
    path('pending', views.pending,name='pending'),
    path('history', views.history,name='history'),
]

hrms-project/hrmanagement_system/employer/urls.py
from . import views
from django.urls import path

app_name = 'employer'

urlpatterns = [
    path('master', views.master,name='master'),
    path('home', views.homepage,name='home'),
    path('departmentlist', views.departmentList,name='departmentlist'),
    path('positionlist', views.positionList,name='positionlist'),
    path('deleteposition/<int:pid>', views.deleteposition,name='deleteposition'),
    path('updatePos', views.updatePos,name='updatePos'),
    path('deleteDepart/<int:pid>', views.deleteDepart,name='deleteDepart'),
    path('employeelist', views.employeeList,name='employeelist'),
    path('employeeadd', views.employeeAdd,name='employeeadd'),
    path('selectPos', views.selectPos,name='selectPos'),

    
]

hrms-project/hrmanagement_system/hrmanagement_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include('employee.urls')),
    path('employer/',include('employer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hrms-project/hrmanagement_system/employer/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    dpartment_name = models.CharField(max_length =250)

    class Meta:
        db_table = 'department_tb'


class Position(models.Model):
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    position_name = models.CharField(max_length =250)

    class Meta:
        db_table = 'position_tb'

class EmployeePersonalProfile(models.Model):
    firstName = models.CharField(max_length =250)
    lastName = models.CharField(max_length =250)
    dateBirth = models.DateField()
    empEmail = models.CharField(max_length =250)
    contactNo = models.BigIntegerField()
    gender = models.CharField(max_length=20)
    permanentAddress = models.CharField(max_length =250)
    localAddress = models.CharField(max_length =250)
    empPhoto = models.ImageField(upload_to='employee/')
    fatherName = models.CharField(max_length =250)
    motherName = models.CharField(max_length =250)
    homeContact = models.BigIntegerField()
    martialStatus = models.CharField(max_length =20)
    spouseName = models.CharField(max_length =250)


class EmployeeCompanyProfile(models.Model):
    employee = models.ForeignKey(EmployeePersonalProfile,on_delete=models.CASCADE)
    accountHolderName = models.CharField(max_length =250)
    accountNumber = models.BigIntegerField()
    bankName = models.CharField(max_length =250)
    branch = models.CharField(max_length =250)
    department_fk = models.ForeignKey(Department,on_delete=models.CASCADE)
    position_fk = models.ForeignKey(Position,on_delete=models.CASCADE)
    reportingManger = models.CharField(max_length =250)
    dateJoining = models.DateField() 
    basicSalary =models.BigIntegerField()
    employeeID = models.CharField(max_length =250)
    Password = models.CharField(max_length = 250)

hrms-project/hrmanagement_system/employer/views.py
from django.shortcuts import render,redirect
from .models import Department,Position,EmployeePersonalProfile,EmployeeCompanyProfile
from django.http import JsonResponse
# Create your views here.

def master(request):
    return render(request,'employer/master.html')


def homepage(request):
    return render(request,'employer/home.html')


def departmentList(request):
    department_details = Department.objects.all()
    if request.method == 'POST':
        if 'submit' in request.POST:
            department_name =request.POST['deptName']
            new_department = Department(dpartment_name = department_name)
            new_department.save()
        if 'update' in request.POST:
            updated_dep_name = request.POST['deptName']
            dep_id = request.POST['dep_id']
            department = Department.objects.get(id=dep_id)
            department.dpartment_name = updated_dep_name
            department.save()
    return render(request,'employer/departmentList.html',{'department':department_details})


def positionList(request):
    department_details = Department.objects.all()
    position_details = Position.objects.all()
    if request.method == 'POST':
        if 'submit' in request.POST:
            pos_name =request.POST['positionName']
            dep_name =request.POST['depNames']
            new_position = Position(position_name = pos_name, department_id = dep_name)
            new_position.save()
    
        if 'update' in request.POST:
            updated_pos_name = request.POST['posName']
            updated_dep_name = request.POST['posDepart']
            pos_id = request.POST['pos_id']
            position = Position.objects.get(id=pos_id)
            position.position_name = updated_pos_name
            position.department_id = updated_dep_name
            position.save()  
    return render(request,'employer/positionList.html',{'department':department_details,'position':position_details})



def deleteposition(request,pid):
    print(pid)
    Position.objects.filter(id=pid).delete()
    return redirect('employer:positionlist')



def deleteDepart(request,pid):
    print(pid)
    Department.objects.filter(id=pid).delete()
    return redirect('employer:departmentlist')

def updatePos(request):
    if request.method == 'POST':
        edit_id =request.POST['pos_id']
        if edit_id:
            position = Position.objects.filter(id=edit_id).values('position_name','department','id')
            pos_id =position[0]['id']
            p_name = position[0]['position_name']
            department_id = position[0]['department']
            
            return JsonResponse({'p_name':p_name,'department_id':department_id,'pos_id':pos_id})  
        return JsonResponse({'error': 'Invalid request'})



def employeeList(request):
    employee_personal_info = EmployeePersonalProfile.objects.all()
    employee_company_info = EmployeeCompanyProfile.objects.all()

    return render(request,'employer/employeeList.html',{'employee_personal_info':employee_personal_info,'employee_company_info':employee_company_info})

def employeeAdd(request):
    success_msg = ''
    department_details = Department.objects.all()
    position_details = Position.objects.all()
    if request.method == 'POST':
        firstName =request.POST['fname']
        lastName =request.POST['sname']
        dateBirth =request.POST['dob']
        emailID  =request.POST['email']
        contactNo =request.POST['phone']
        gender =request.POST['gender']
        permanentAddress =request.POST['permanentAdd'] 
        localAddress =request.POST['localAdress']
        empPhoto =request.FILES['pic']
        fatherName =request.POST['fatherName']
        empMotherName =request.POST['motherName']
        homeContact =request.POST['contactNumb']
        martialStatus =request.POST['maraggeStatus']
        spouseName =request.POST['spouseName']
        accountHolderName = request.POST['accountHolderName']
        accountNumber =request.POST['accountNumber']
        bankName =request.POST['bankName']
        branch =request.POST['branch']
        department_fk =request.POST['depName']
        position_fk =request.POST['posName']
        reportingManger =request.POST['reportingManger']
        dateJoining =request.POST['dateofjoin']
        basicSalary =request.POST['baseSalary']
        employeeID =request.POST['EmpId']
        Password =request.POST['confPassword']

        employeePersonalProfiles =EmployeePersonalProfile(firstName = firstName,
        lastName =lastName ,dateBirth =dateBirth,empEmail=emailID,contactNo=contactNo,
        gender =gender,permanentAddress =permanentAddress,localAddress=localAddress,
        empPhoto=empPhoto,fatherName=fatherName,motherName=empMotherName,homeContact=homeContact,
        martialStatus=martialStatus,spouseName=spouseName
        )
        employeePersonalProfiles.save()
        employeePersonalID = employeePersonalProfiles.id
        employeeCompanyProfiles = EmployeeCompanyProfile(employee_id =employeePersonalID,accountHolderName =accountHolderName,accountNumber=accountNumber,
        bankName =bankName,branch=branch,department_fk_id=department_fk,position_fk_id=position_fk,reportingManger=reportingManger,
        dateJoining=dateJoining,basicSalary=basicSalary,employeeID=employeeID,Password=Password
        )
        employeeCompanyProfiles.save()
        success_msg = 'successfully created new employee'
   
    return render(request,'employer/employeeadd.html',{'department':department_details,'position':position_details,'success_msg':success_msg})

def selectPos(request):
    if request.method == 'POST':
        dep_id =request.POST['dep_id']
        if dep_id:
            positions =Position.objects.filter(department_id = dep_id).values('position_name','id')
            positions_list = list(positions)  
            return JsonResponse(positions_list, safe=False)

hrms-project/hrmanagement_system/templates/employer/departmentList.html
{% extends 'employer/master.html'%}

{% load static %}

{% block content %}
<div class="container mt-5 pt-3">
<div class="row mt-4 ">
    <div class="col-sm-5">
      <div class="card border-0">
        <div class="card-header text-center bg-primary border-0 text-light  rounded-pill fs-5 ">Add New Department</div>
        <div class="card-body ">
         
            <form method="post" id="myForm">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="departmentAdd" class="form-label">Department Name </label>
                  <input type="text" class="form-control"  name="deptName">
                </div>
                
                <button type="submit" class="btn btn-outline-primary" name="submit">Submit</button>
              </form>

        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="card">
        <div class="card-header text-center bg-primary text-light fs-5 ">Department List</div>
        <div class="card-body">
            <table class="table ">
                <thead>
                  <tr>
                    <th>Sno</th>
                    <th>Department</th>
                    <th>Action</th>
                    
                  </tr>
                </thead>
                <tbody>
            {% for dep in department %}    
                  <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ dep.dpartment_name }}</td>
                    <td hidden>{{ dep.id }}</td>
                    <td><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="departFech()">edit</button> <a href="{% url 'employer:deleteDepart' dep.id %}" class="btn btn-outline-danger">Delete</a></td>
                  </tr>
                  {% endfor %}      
                </tbody>
              </table>
        </div>
      </div>
    </div>
  </div>
</div>


 <!-- Modal -->
 <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post">
              {% csrf_token %}
              <input type="hidden" name="dep_id" id="dep_id">
                <div class="mb-3">
                    <label for="departmentAdd" class="form-label">Department Name </label>
                    <input type="text" class="form-control" id="departmentAdd" name="deptName" >
                  </div> 
                
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" name="update">Update</button>
        </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    function departFech(){
      var selected_row = event.target.parentNode.parentNode
      var children = selected_row.childNodes
      // console.log(children)
      var modal_text =document.getElementById('departmentAdd') 
      var modal_hidden =document.getElementById('dep_id')
      modal_hidden.value =children[5].innerText
      modal_text.value =children[3].innerText
    }

  </script>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->



<script>
  $(document).ready(function () {
      
      $('#myForm').validate({
        
          rules: {
            deptName: {
                  required: true
              },
              
            
          },
          messages: {
            deptName: 'Please enter department name',
             
            
          }
         
      });
  });
</script>
{% endblock %}

hrms-project/hrmanagement_system/templates/employer/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Employer dashboard</title>

<!-- --------------------------bootstrap link--------------------------------------- -->

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  
<!-- --------------------------google font--------------------------------------- -->
  <link
  href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,700&display=swap"
  rel="stylesheet">

<!-- -------------------------------------fontawsome----------------------------------------- -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  
  
<!-- -----------------css link------------------------------------------- -->
  
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> --> -->


  <link rel="stylesheet" href="{% static 'style/dashboard.css' %}">

  <link rel="stylesheet" href="{% static 'style/calender.css' %}">

  <link rel="stylesheet" href="{% static 'style/attendence.css' %}">

  <link rel="stylesheet" href="{% static 'style/leave.css' %}">



  




<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"> -->
      
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>

<style>
  .myhover:hover{
color: white !important;


}
.error{
  color: red !important;
}
</style>

<body>
  <nav class="navbar navbar-expand-lg  bg-light  fixed-top">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="#offcanvasScrolling" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand text-primary fs-3 fw-bold" href="#">HR<span class="text-uppercase text-dark fs-5"> Mithra</span></a>
      <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
        
        <!-- <form class="d-flex ms-auto mt-3 mt-lg-0" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      
      <div class="dropdown mx-lg-4">
        <button class="btn  dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-user"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="{% url 'employee:hrlogin' %}">Log Out</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Enable body scrolling</button> -->
  <div class="offcanvas offcanvas-start sidebar-nav rounded-4 border-0" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header text-dark">
      <h5 class="offcanvas-title" id="offcanvasScrollingLabel"></h5>
    </div>
    <div class="offcanvas-body text-secondary">
      <ul class="navbar-nav" id="nav-bar-item">
        <li class="nav-item">
          <a class="nav-link d-flex" aria-current="page" href="home">
            <i class="fa-solid fa-house me-3 fs-6"></i>
            <p class="fs-6">Home</p>
            
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex" data-bs-toggle="collapse" href="#payrollCollapse" role="button" aria-expanded="false" aria-controls="payrollCollapse">
            <i class="fa-solid fa-hand-holding-dollar me-2 fs-5"></i>
            <p class="fs-6">Payroll</p>
            <i class="fas fa-chevron-down ms-auto "></i>
          </a>
          <div class="collapse mt-0" id="payrollCollapse">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link ms-4" href="#">Sub-item 1</a>
              </li>
              <li class="nav-item">
                <a class="nav-link ms-4" href="#">Sub-item 2</a>
              </li>
            </ul>
          </div>
        </li>
      </li>
      <li class="nav-item">
        <a class="nav-link d-flex" data-bs-toggle="collapse" href="#employeeCollapse" role="button" aria-expanded="false" aria-controls="employeeCollapse">
          <i class="fa-solid fa-user me-3 fs-6"></i>
          <p class="fs-6">Employee</p>
          <i class="fas fa-chevron-down ms-auto "></i>
        </a>
        <div class="collapse mt-0" id="employeeCollapse">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link ms-4" href="employeelist">Employee List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link ms-4" href="departmentlist">Department List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link ms-4" href="positionlist">Position List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link ms-4" href="#">Allowence List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link ms-4" href="#">Deduction List</a>
            </li>
          </ul>
        </div>
      </li>
        <li class="nav-item">
          <a class="nav-link d-flex" aria-current="page" href="">
            
            <p class="fs-6">attendence</p>
            
          </a>
        </li>
      </ul>
    </div>
  </div>
  
  <main>
  {% block content %}

  {% endblock %}
  </main>

  <script src="{% static 'javascript/hover.js' %}"></script>
  
  <script src="{% static 'javascript/table.js' %}"></script>

<!-- --------------------------------------js file table------------------------------------------------------- -->

  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<!-- --------------------------------------js file calender------------------------------------------------------- -->

  <script src="{% static 'javascript/calender.js' %}"></script>  

<!-- --------------------------------------js file date------------------------------------------------------- -->

  <script src="{% static 'javascript/date.js' %}"></script>
<!-- --------------------------------------js file calender-io------------------------------------------------------- -->

  <!-- <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.0/main.js"></script> -->

<!-- --------------------------------------js file bootstrap------------------------------------------------------- -->

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="{% static 'javascript/employer_table.js' %}"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/additional-methods.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/additional-methods.min.js"></script>
</body>
</html>

hrms-project/hrmanagement_system/templates/employer/positionList.html
{% extends 'employer/master.html'%}

{% load static %}

{% block content %}

<div class="container mt-5 pt-5">

    <div class="row mt-4 ">
        <div class="col-sm-5">
          <div class="card border-0">
            <div class="card-header text-center bg-primary border-0 text-light  rounded-pill fs-5 ">Add New Department</div>
            <div class="card-body ">
             
                <form method="post" id="myForm">
                  {% csrf_token %}
                    <div class="mb-3">
                      <label for="positionAdd" class="form-label">Position Name </label>
                      <input type="text" class="form-control" id="positionAdd"  name="positionName">
                    </div>
                    <div class="mb-3">
                        <label for="positionAdd" class="form-label">Department</label>
                        <select class="form-select"  name="depNames">
                            <option value="">select one</option>
                            {% for dep in department %} 
                            <option value="{{ dep.id }}">{{ dep.dpartment_name }}</option>
                            {% endfor %}
                          </select>
                      </div>
                    
                    <button type="submit" class="btn btn-outline-primary" name="submit">Submit</button>
                  </form>
    
            </div>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="card">
            <div class="card-header text-center bg-primary text-light fs-5 ">Position List</div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                    <thead>
                      <tr>
                        <th>Sno</th>
                        <th>Position</th>
                        <th>Department</th>
                        <th>Action</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                      {% for pos in position %}
                      <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ pos.position_name }}</td>
                        <td>{{ pos.department.dpartment_name }}</td>
                        <td hidden > {{ pos.id }} </td>
                        <td><button type="button"  class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop" id="btn">edit</button> <a href="{% url 'employer:deleteposition' pos.id %}" class="btn btn-outline-danger">Delete</a></td>
                      </tr>
                      {% endfor %} 
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
      </div>
</div>




  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post">
              {% csrf_token %}
                <div class="mb-3">
                  <input type="text" name="pos_id" id="positionId" hidden>
                  <label for="positionAdd" class="form-label">Position Name </label>
                  <input type="text" class="form-control" id="positionAjax"  name="posName">
                </div>
                <div class="mb-3">
                    <label for="positionAdd" class="form-label">Department</label>
                    <select class="form-select" id="posSelect" name="posDepart" >
                        <option selected>select one</option>
                        {% for dep in department %} 
                        <option value="{{ dep.id }}">{{ dep.dpartment_name }}</option>
                        {% endfor %}
                      </select>
                  </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" name="update">Update</button>
        </form>
        </div>
      </div>
    </div>
  </div>

  
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      $.ajaxSetup({
              headers: {
                "X-CSRFToken": '{{ csrf_token }}'
              }
          })
      $(".btn").click(function(){
        var posId = $(this).closest('tr').find('td:hidden').text();
           
            // console.log(posId)
            $.ajax({
              url:"{% url 'employer:updatePos' %}",
              data:{
                'pos_id':posId ,
                 
  
              },
              method : 'POST',
              dataType: 'json',
              success: function(response){
                // console.log(response.department_id)
                $('#positionId').val(response.pos_id)
                $('#positionAjax').val(response.p_name)
                $("#posSelect").val(response.department_id);
                // $('#current_stock').val(response.pstock)
              
                
              }
              
              
            })
          })
          
    })
  </script>

<script>
  $(document).ready(function () {
      
      $('#myForm').validate({
        
          rules: {
            positionName: {
                  required: true
              },
              depNames: {
                required: true
              }
            
          },
          messages: {
            positionName: {
              required:'Please enter position name' 
            },
            depNames: {
              required:'please select department'
            } 
            
          }
         
      });
  });
</script>
{% endblock %}